### ISSUE TITLE
False Positive IPs

### ISSUE THREAD

**Issue by n2x4** [wallacepalace/rules-siem-elastic#1]
I've been testing the rulesets, seeing some IPs that I'm not confident are accurate -

34.202.33.33 - Rule says its from Talos and AbusedIPDB - Neither service have this address listed and it appears to be a legitimate IP address check service for AWS.

151.139.128.14 - Rule says its from Talos and AbusedIPDB - AbusedIPDB has this address listed but it appears to be a legitimate IP address for sectigo and stackpath CDN services.

**Comment by wallacepalace** [comment]
> I've been testing the rulesets, seeing some IPs that I'm not confident are accurate -
> 
> 34.202.33.33 - Rule says its from Talos and AbusedIPDB - Neither service have this address listed and it appears to be a legitimate IP address check service for AWS.
> 
> 151.139.128.14 - Rule says its from Talos and AbusedIPDB - AbusedIPDB has this address listed but it appears to be a legitimate IP address for sectigo and stackpath CDN services.

Thanks, n2, i will doublecheck following ur comment and delete the 2 ips. They may have already been seen in a campaign, so I put it on.
